// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/branch.proto

package branch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_proto_branch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_branch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_proto_branch_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBranchRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchResponse) Reset() {
	*x = CreateBranchResponse{}
	mi := &file_proto_branch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchResponse) ProtoMessage() {}

func (x *CreateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_branch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchResponse.ProtoReflect.Descriptor instead.
func (*CreateBranchResponse) Descriptor() ([]byte, []int) {
	return file_proto_branch_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBranchResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateBranchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchRequest) Reset() {
	*x = GetBranchRequest{}
	mi := &file_proto_branch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchRequest) ProtoMessage() {}

func (x *GetBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_branch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchRequest.ProtoReflect.Descriptor instead.
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return file_proto_branch_proto_rawDescGZIP(), []int{2}
}

func (x *GetBranchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchResponse) Reset() {
	*x = GetBranchResponse{}
	mi := &file_proto_branch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchResponse) ProtoMessage() {}

func (x *GetBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_branch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchResponse.ProtoReflect.Descriptor instead.
func (*GetBranchResponse) Descriptor() ([]byte, []int) {
	return file_proto_branch_proto_rawDescGZIP(), []int{3}
}

func (x *GetBranchResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBranchResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBranchResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_branch_proto protoreflect.FileDescriptor

const file_proto_branch_proto_rawDesc = "" +
	"\n" +
	"\x12proto/branch.proto\x12\x10grpcserver.proto\"C\n" +
	"\x13CreateBranchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"@\n" +
	"\x14CreateBranchResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\x10GetBranchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x11GetBranchResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress2\xc4\x01\n" +
	"\rBranchService\x12]\n" +
	"\fCreateBranch\x12%.grpcserver.proto.CreateBranchRequest\x1a&.grpcserver.proto.CreateBranchResponse\x12T\n" +
	"\tGetBranch\x12\".grpcserver.proto.GetBranchRequest\x1a#.grpcserver.proto.GetBranchResponseB\x0fZ\r/proto;branchb\x06proto3"

var (
	file_proto_branch_proto_rawDescOnce sync.Once
	file_proto_branch_proto_rawDescData []byte
)

func file_proto_branch_proto_rawDescGZIP() []byte {
	file_proto_branch_proto_rawDescOnce.Do(func() {
		file_proto_branch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_branch_proto_rawDesc), len(file_proto_branch_proto_rawDesc)))
	})
	return file_proto_branch_proto_rawDescData
}

var file_proto_branch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_branch_proto_goTypes = []any{
	(*CreateBranchRequest)(nil),  // 0: grpcserver.proto.CreateBranchRequest
	(*CreateBranchResponse)(nil), // 1: grpcserver.proto.CreateBranchResponse
	(*GetBranchRequest)(nil),     // 2: grpcserver.proto.GetBranchRequest
	(*GetBranchResponse)(nil),    // 3: grpcserver.proto.GetBranchResponse
}
var file_proto_branch_proto_depIdxs = []int32{
	0, // 0: grpcserver.proto.BranchService.CreateBranch:input_type -> grpcserver.proto.CreateBranchRequest
	2, // 1: grpcserver.proto.BranchService.GetBranch:input_type -> grpcserver.proto.GetBranchRequest
	1, // 2: grpcserver.proto.BranchService.CreateBranch:output_type -> grpcserver.proto.CreateBranchResponse
	3, // 3: grpcserver.proto.BranchService.GetBranch:output_type -> grpcserver.proto.GetBranchResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_branch_proto_init() }
func file_proto_branch_proto_init() {
	if File_proto_branch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_branch_proto_rawDesc), len(file_proto_branch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_branch_proto_goTypes,
		DependencyIndexes: file_proto_branch_proto_depIdxs,
		MessageInfos:      file_proto_branch_proto_msgTypes,
	}.Build()
	File_proto_branch_proto = out.File
	file_proto_branch_proto_goTypes = nil
	file_proto_branch_proto_depIdxs = nil
}
